spring:
  application:
    name: servarium

  liquibase:
    change-log: classpath:db/changelog/auth/main-changelog.yaml

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

      max-lifetime: 1_200_000 # 20 мин
      connection-timeout: 15_000
      idle-timeout: 300_000 # 5 минут

      validation-timeout: 3_000

      leak-detection-threshold: 10_000
      auto-commit: false